apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::729430245727:role/eksctl-eksctl-demokml-nodegroup-n-NodeInstanceRole-1WCN2AFUK6UD2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::729430245727:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-06T21:19:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-06T21:19:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1315"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3f501373-d2f1-464a-b8b4-10b2f1be5f20
