apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::545118085105:role/eksctl-kmlawlors-eks-api-nodegrou-NodeInstanceRole-70FL7OEOCW48
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-02T20:55:56Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-02T20:55:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1369"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9bcd30c4-422d-48c1-8335-dca1ecdf62a7
